# Generated by Django 5.1.4 on 2024-12-29 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dpi_manager', '0006_alter_dpi_medecin_traitant_delete_medecin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Soins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('soins_donnés', models.TextField()),
                ('notes', models.TextField()),
                ('dpi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soins', to='dpi_manager.dpi')),
            ],
        ),
    ]
