# Generated by Django 5.1.3 on 2025-01-01 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consultations', '0002_alter_consultation_certificat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Soins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('soins_donnés', models.TextField()),
                ('notes', models.TextField()),
                ('consultation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='soins', to='consultations.consultation')),
            ],
        ),
    ]
