# Generated by Django 5.1.4 on 2024-12-31 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0002_alter_consultation_certificat_and_more'),
        ('soins', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soins',
            name='dpi',
        ),
        migrations.AddField(
            model_name='soins',
            name='consultation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='soins', to='consultations.consultation'),
        ),
    ]
