# Generated by Django 5.1.3 on 2025-01-01 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soins', '0002_soins_infirmier'),
        ('users', '0006_infirmier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soins',
            name='infirmier',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='soins_infirmier', to='users.infirmier'),
        ),
    ]
