# Generated by Django 5.1.3 on 2025-01-01 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soins', '0004_alter_soins_consultation'),
        ('users', '0006_infirmier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soins',
            name='infirmier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.infirmier'),
        ),
    ]
