# Generated by Django 5.1.4 on 2024-12-29 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0002_alter_consultation_certificat_and_more'),
        ('sgph', '0002_alter_ordonnance_consultation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordonnance',
            name='consultation',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ordonnance', to='consultations.consultation'),
        ),
    ]
