# Generated by Django 5.1.3 on 2024-12-30 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgph', '0002_alter_ordonnance_consultation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicament',
            name='duration',
            field=models.CharField(max_length=20),
        ),
    ]
