# Generated by Django 5.1.4 on 2024-12-29 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgph', '0003_alter_ordonnance_consultation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicament',
            name='ordonnance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medicaments', to='sgph.ordonnance'),
        ),
    ]
