# Generated by Django 5.1.4 on 2024-12-29 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='certificat',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consultation', to='consultations.certificat'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='frais',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consultation', to='consultations.frais'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='resume',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consultation', to='consultations.resume'),
        ),
    ]
