# Generated by Django 5.1.4 on 2024-12-23 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bilan', '0001_initial'),
        ('consultations', '0001_initial'),
        ('users', '0005_laborantin_radiologue'),
    ]

    operations = [
        migrations.AddField(
            model_name='bilanbiologique',
            name='consultation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='consultations.consultation'),
        ),
        migrations.AddField(
            model_name='bilanbiologique',
            name='laborantin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bilans_biologiques_laborantin', to='users.laborantin'),
        ),
        migrations.AddField(
            model_name='bilanradiologique',
            name='consultation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='consultations.consultation'),
        ),
        migrations.AddField(
            model_name='bilanradiologique',
            name='radiologue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bilans_radiologiques_radiologue', to='users.radiologue'),
        ),
        migrations.AddField(
            model_name='imagemedical',
            name='bilan_radiologique',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='image_medical', to='bilan.bilanradiologique'),
        ),
    ]
