# Generated by Django 5.1.3 on 2024-12-29 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bilan', '0003_alter_bilanbiologique_graphique_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bilanbiologique',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='bilanradiologique',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
