# Generated by Django 5.1.3 on 2024-12-30 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bilan', '0006_alter_bilanbiologique_result'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bilanbiologique',
            name='test_type',
        ),
        migrations.AddField(
            model_name='bilanbiologique',
            name='type_bilan',
            field=models.CharField(choices=[('Bilan sanguin', 'Bilan sanguin'), ("Bilan d'urine", "Bilan d'urine"), ('Bilan hepatique', 'Bilan hépatique'), ('Bilan renal', 'Bilan rénal')], default='Bilan sanguin', max_length=100),
        ),
    ]
