# Generated by Django 5.1.3 on 2024-12-30 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bilan', '0007_remove_bilanbiologique_test_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bilanbiologique',
            old_name='type_bilan',
            new_name='test_type',
        ),
    ]
