# Generated by Django 5.1.3 on 2024-12-30 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bilan', '0008_rename_type_bilan_bilanbiologique_test_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bilanbiologique',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='bilanradiologique',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
