# Generated by Django 5.1.3 on 2024-12-20 19:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medecin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('date_naissance', models.DateField()),
                ('adresse', models.TextField()),
                ('telephone', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mot_de_passe', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('date_naissance', models.DateField()),
                ('adresse', models.TextField()),
                ('telephone', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('numero_securite_sociale', models.CharField(max_length=50, unique=True)),
                ('mot_de_passe', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Dpi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mutuelle', models.CharField(max_length=100)),
                ('telephone_personne_contact', models.CharField(max_length=15)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dpi_crees', to=settings.AUTH_USER_MODEL)),
                ('medecin_traitant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dossiers', to='dpi_manager.medecin')),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dpi', to='dpi_manager.patient')),
            ],
        ),
    ]
