# Generated by Django 5.1.3 on 2024-12-21 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpi_manager', '0002_rename_numero_securite_sociale_patient_nss'),
    ]

    operations = [
        migrations.AddField(
            model_name='dpi',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
    ]
