# Generated by Django 5.1.4 on 2024-12-21 20:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpi_manager', '0002_rename_numero_securite_sociale_patient_nss'),
        ('users', '0003_patient'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='dpi',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dpi', to='users.patient'),
        ),
        migrations.RemoveField(
            model_name='medecin',
            name='email',
        ),
        migrations.RemoveField(
            model_name='medecin',
            name='mot_de_passe',
        ),
        migrations.RemoveField(
            model_name='medecin',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='medecin',
            name='prenom',
        ),
        migrations.AddField(
            model_name='medecin',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medecin_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
